/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\GLB\Bookshelf.glb --output output\Bookshelf.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Google/Models/Bookshelf.glb`;

export function ModelGoogleBookshelf(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh name="Shelf" castShadow receiveShadow geometry={nodes.Shelf.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload(link)
