/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\GLB\Camp Fire.glb --output output\Camp Fire.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Google/Models/Camp Fire.glb`;

export function ModelGoogleCampFire(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh name="Campfire" castShadow receiveShadow geometry={nodes.Campfire.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload(link)
