/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\models\Couch.glb --output output\Couch.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/J-Toastie/Models/Couch.glb`;

export function ModelJToastieCouch(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh name="couch" castShadow receiveShadow geometry={nodes.couch.geometry} material={materials.Couch} position={[0, 0.084, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[48, 52.964, 48]} />
    </group>
  )
}

useGLTF.preload(link)
