/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\GLB\Shoes1.glb --output output\Shoes1.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Google/Models/Shoes1.glb`;

export function ModelGoogleShoes1(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh name="Node-Mesh" castShadow receiveShadow geometry={nodes['Node-Mesh'].geometry} material={materials.lambert4SG} />
      <mesh name="Node-Mesh_1" castShadow receiveShadow geometry={nodes['Node-Mesh_1'].geometry} material={materials.lambert5SG} />
      <mesh name="Node-Mesh_2" castShadow receiveShadow geometry={nodes['Node-Mesh_2'].geometry} material={materials.lambert6SG} />
      <mesh name="Node-Mesh_3" castShadow receiveShadow geometry={nodes['Node-Mesh_3'].geometry} material={materials.lambert7SG} />
    </group>
  )
}

useGLTF.preload(link)
