/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\tableGlass.glb --output output\tableGlass.js --transform 
Files: models\tableGlass.glb [9.85KB] > E:\Downloads\kenney_furniture-kit\JSX\output\tableGlass-transformed.glb [2.32KB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Furniture/Models/tableGlass-transformed.glb`;

export function ModelKennyNLFurnitureTableGlass(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_tableGlass.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_tableGlass_1.geometry} material={materials.glass} />
    </group>
  )
}

useGLTF.preload(link)
