/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chicken.glb -T 
Files: chicken.glb [103.74KB] > F:\My Documents\Sites\games\games-showcase\public\models\Minecraft\chicken-transformed.glb [4.82KB] (95%)
Author: ArthurKnoepflin (https://sketchfab.com/ArthurKnoepflin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chicken-from-minecraft-8e9159f320624de193242a6aeccce091
Title: Chicken from Minecraft
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelMinecraftChicken(props) {
  const { nodes, materials } = useGLTF('models/Minecraft/chicken-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} position={[-0.107, -0.214, 0.214]} scale={[0.053, 0.214, 0.053]} />
    </group>
  )
}

useGLTF.preload('models/Minecraft/chicken-transformed.glb')
