/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 creeper.glb -T 
Files: creeper.glb [10.74KB] > F:\My Documents\Sites\games\games-showcase\public\models\Minecraft\creeper-transformed.glb [3.08KB] (71%)
Author: Vincent Yanez (https://sketchfab.com/vinceyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-creeper-fd66182f07e5408eb04fa5a88ae16055
Title: Minecraft - Creeper
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelMinecraftCreeper(props) {
  const { nodes, materials } = useGLTF('models/Minecraft/creeper-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Creeper_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[0, -7, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/Minecraft/creeper-transformed.glb')
