/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 diamond_axe.glb -T 
Files: diamond_axe.glb [145.67KB] > F:\My Documents\Sites\games\games-showcase\public\models\Minecraft\diamond_axe-transformed.glb [60.88KB] (58%)
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-diamond-axe-0d62f4d3676545c88ec8523213c055dd
Title: Minecraft Diamond Axe
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelMinecraftDiamondAxe(props) {
  const { nodes, materials } = useGLTF('models/Minecraft/diamond_axe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.009']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/Minecraft/diamond_axe-transformed.glb')
