/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 steve.glb -T 
Files: steve.glb [284.23KB] > F:\My Documents\Sites\games\games-showcase\public\models\Minecraft\steve-transformed.glb [55.58KB] (80%)
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-perfect-steve-rigged-0cffc39bdab04551bde4f8cdfbc52eca
Title: The Perfect Steve Rigged
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelMinecraftSteve(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/Minecraft/steve-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  console.log("Available animations for Steve:", Object.keys(actions));

  useEffect(() => {
    if (actions['Armature.001|Walk']) {
      actions['Armature.001|Walk'].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials['Scene_-_Root']} skeleton={nodes.Object_27.skeleton} position={[-0.347, -204.182, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Minecraft/steve-transformed.glb')
