/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wooden_door.glb -T 
Files: wooden_door.glb [209.84KB] > F:\My Documents\Sites\games\games-showcase\public\models\Minecraft\wooden_door-transformed.glb [28.71KB] (86%)
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-wooden-door-b5e5426ac8554d6690846c5150ec81b6
Title: Minecraft Wooden Door
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelMinecraftWoodenDoor(props) {
  const { nodes, materials } = useGLTF('models/Minecraft/wooden_door-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Object_2.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/Minecraft/wooden_door-transformed.glb')
