/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 easel.glb -T 
Files: easel.glb [8.86KB] > F:\My Documents\Sites\games\games-showcase\public\models\easel-transformed.glb [2.44KB] (72%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelEasel(props) {
  const { nodes, materials } = useGLTF('models/easel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1441049998.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1958263894.geometry} material={materials.mat20} />
    </group>
  )
}

useGLTF.preload('models/easel-transformed.glb')
