/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fortnite_peely_skin.glb -T 
Files: fortnite_peely_skin.glb [1.43MB] > F:\My Documents\Sites\games\games-showcase\public\models\fortnite_peely_skin-transformed.glb [108.6KB] (92%)
Author: Neut2000 (https://sketchfab.com/Neut2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fortnite-peely-skin-79c243d64f0d4c74a6a78e6965d9b87a
Title: Fortnite Peely Skin
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelFortnitePeelySkin(props) {
  const { nodes, materials } = useGLTF('models/Fortnite/fortnite_peely_skin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_7.geometry} material={materials.M_MED_Banana_Body} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/Fortnite/fortnite_peely_skin-transformed.glb')
