/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 halo_warthog.glb -T 
Files: halo_warthog.glb [12.97MB] > F:\My Documents\Sites\games\games-showcase\public\models\Halo\halo_warthog-transformed.glb [1.82MB] (86%)
Author: pinto36 (https://sketchfab.com/pinto36)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/halo-warthog-bd3403bc06884260ac31d0e98eed81e4
Title: Halo Warthog
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelHaloWarthog(props) {
  const { nodes, materials } = useGLTF('models/Halo/halo_warthog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Body_Green1} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Body_Under1} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Seats1} />
    </group>
  )
}

useGLTF.preload('models/Halo/halo_warthog-transformed.glb')
