/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 maze_board.glb -T 
Files: maze_board.glb [171.38KB] > D:\Downloads\maze_board-transformed.glb [6.17KB] (96%)
Author: artmaeham (https://sketchfab.com/artmaeham)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maze-board-0a1e67906ba14e168896208c8c778fbc
Title: Maze Board
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useTrimesh, useSphere } from '@react-three/cannon'
import { Vector3, Quaternion, Euler } from 'three'

export function ModelMazeBoard({ scale = 1, ...props }) {
  const { nodes, materials } = useGLTF('models/maze_board-transformed.glb')
  
  const initialPos = useMemo(() => new Vector3(-1.318, 0, 0.007), [])
  const initialRot = useMemo(() => new Euler(-Math.PI / 2, 0, -3.136), [])
  
  const finalScale = scale * 0.01

  const [pinkRef, pinkApi] = useTrimesh(() => ({
    args: [nodes.BoardMesh_Pink_0.geometry.attributes.position.array, nodes.BoardMesh_Pink_0.geometry.index.array],
    position: [initialPos.x, initialPos.y, initialPos.z],
    rotation: [initialRot.x, initialRot.y, initialRot.z],
    scale: [finalScale, finalScale, finalScale],
    type: 'Kinematic'
  }))

  const [blueRef, blueApi] = useTrimesh(() => ({
    args: [nodes.BoardMesh_Blue_0.geometry.attributes.position.array, nodes.BoardMesh_Blue_0.geometry.index.array],
    position: [initialPos.x, initialPos.y, initialPos.z],
    rotation: [initialRot.x, initialRot.y, initialRot.z],
    scale: [finalScale, finalScale, finalScale],
    type: 'Kinematic'
  }))

  useFrame((state) => {
    const time = state.clock.getElapsedTime()
    const angle = time * 0.2

    const yAxis = new Vector3(0, 1, 0)
    const newPos = initialPos.clone().applyAxisAngle(yAxis, angle)

    const qBase = new Quaternion().setFromEuler(initialRot)
    const qRot = new Quaternion().setFromAxisAngle(yAxis, angle)
    const qFinal = qRot.multiply(qBase)

    pinkApi.position.set(newPos.x, newPos.y, newPos.z)
    pinkApi.quaternion.set(qFinal.x, qFinal.y, qFinal.z, qFinal.w)

    blueApi.position.set(newPos.x, newPos.y, newPos.z)
    blueApi.quaternion.set(qFinal.x, qFinal.y, qFinal.z, qFinal.w)
  })

  return (
    <group {...props} dispose={null}>
      <mesh ref={pinkRef} geometry={nodes.BoardMesh_Pink_0.geometry} material={materials.Pink} />
      <mesh ref={blueRef} geometry={nodes.BoardMesh_Blue_0.geometry} material={materials.Blue} />
    </group>
  )
}

export function MazeBall(props) {
  const [ref] = useSphere(() => ({ mass: 1, args: [6], ...props, position: [0, 10, 0] }))

  return (
    <mesh ref={ref} castShadow receiveShadow>
      <sphereGeometry args={[6, 32, 32]} />
      <meshStandardMaterial color="yellow" />
    </mesh>
  )
}

useGLTF.preload('models/maze_board-transformed.glb')
