/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rock.glb -T 
Files: rock.glb [3.07MB] > F:\My Documents\Sites\games\games-showcase\public\models\rock-transformed.glb [50.72KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelRock(props) {
  const { nodes, materials } = useGLTF('models/rock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_5.geometry} material={materials.Rock} position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={props.scale} />
    </group>
  )
}

useGLTF.preload('models/rock-transformed.glb')
