/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\Swat.gltf --output output\Swat.js --transform 
Files: models\Swat.gltf [3.37MB] > E:\Downloads\men\output\Swat-transformed.glb [772.98KB] (77%)
*/

import React, { useEffect, useState } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelGlassCeilingSwat(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/Battlefield 4/Swat-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, mixer } = useAnimations(animations, group)
  // const [flash, setFlash] = useState(false);

  console.log("Available animations:", Object.keys(actions));

  useEffect(() => {
      if (actions["Sword_Slash"]) {
        const action = actions['Sword_Slash'];
        // Randomize start time to desync multiple instances
        action.time = Math.random() * action.getClip().duration;
        action.play();
      }

      const handleLoop = (e) => {
        if (e.action === actions['Sword_Slash']) {
          // setFlash(true);
          // setTimeout(() => setFlash(false), 50);
        }
      };

      mixer.addEventListener('loop', handleLoop);
      return () => mixer.removeEventListener('loop', handleLoop);

    }, [actions, mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        {/* <group name="Pistol">
          <pointLight position={[0, 0.2, 0.5]} intensity={flash ? 20 : 0} color="orange" distance={3} decay={2} />
          <skinnedMesh name="Cube204" geometry={nodes.Cube204.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube204.skeleton} />
          <skinnedMesh name="Cube204_1" geometry={nodes.Cube204_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube204_1.skeleton} />
          <skinnedMesh name="Cube204_2" geometry={nodes.Cube204_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube204_2.skeleton} />
        </group> */}
        <group name="Swat_Body">
          <skinnedMesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube018.skeleton} />
          <skinnedMesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube018_1.skeleton} />
          <skinnedMesh name="Cube018_2" geometry={nodes.Cube018_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube018_2.skeleton} />
        </group>
        <skinnedMesh name="Swat_Feet" geometry={nodes.Swat_Feet.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Swat_Feet.skeleton} />
        <group name="Swat_Head">
          <skinnedMesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube037.skeleton} />
          <skinnedMesh name="Cube037_1" geometry={nodes.Cube037_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube037_1.skeleton} />
          <skinnedMesh name="Cube037_2" geometry={nodes.Cube037_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube037_2.skeleton} />
        </group>
        <group name="Swat_Legs">
          <skinnedMesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube023.skeleton} />
          <skinnedMesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube023_1.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/Battlefield 4/Swat-transformed.glb')
