/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Four%20Frogs/Orange Flower.glb`

export function OrangeFlower(props) {
    const { nodes, materials } = useGLTF(link);
    return (
        <group {...props} dispose={null}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["hibiscus_flower-Mesh"].geometry}
            material={materials.red}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["hibiscus_flower-Mesh_1"].geometry}
            material={materials.hay}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["hibiscus_flower-Mesh_2"].geometry}
            material={materials.tree}
          />
        </group>
      );
}

useGLTF.preload(link);
