/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Four%20Frogs/Sunflower.glb`

export function Sunflower(props) {

    const { nodes, materials } = useGLTF(link);

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.sunflower?.geometry}
                material={materials.None}
            />
        </group>
    );
}

useGLTF.preload(link);
