/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pinball.glb -T 
Files: pinball.glb [1.26MB] > F:\My Documents\Sites\games\games-showcase\public\models\Carousel of Progress\pinball-transformed.glb [131.4KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelPinballMachine(props) {
  const { nodes, materials } = useGLTF('models/Pinball/pinball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Poliigon_WoodVeneerOak_7760_1K} position={[-2.86, 4, 7.194]} scale={[0.336, 4, 1]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Poliigon_MetalSteelBrushed_7174_1K} position={[0, 10.309, -0.772]} rotation={[0.286, 0, 0]} scale={[1, 1, 9.639]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.PaletteMaterial001} position={[-2.86, 16.353, -9.739]} scale={[1.135, 4, 1]} />
    </group>
  )
}

useGLTF.preload('models/Pinball/pinball-transformed.glb')
