/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Building 1-transformed.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelBuildingOne(props) {
  const { nodes, materials } = useGLTF('models/Eager Eagle/Building 1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.3, 0]}>
        <mesh geometry={nodes.skyscraper.geometry} material={materials.None} />
      </group>     
    </group>
  )
}

useGLTF.preload('models/Eager Eagle/Building 1-transformed.glb')
