/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Eagle.glb -T 
Files: Eagle.glb [502.71KB] > F:\My Documents\Sites\games\games-showcase\public\models\Eager Eagle\Eagle-transformed.glb [23.27KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelEagle(props) {
  const { nodes, materials } = useGLTF('models/Eager Eagle/Eagle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.eagle_head} />
      <mesh geometry={nodes.Cylinder001_1_1.geometry} material={materials.eagle_body} />
      <mesh geometry={nodes.Cylinder001_1_2.geometry} material={materials.eagle_tail} />
      <mesh geometry={nodes.Cylinder001_1_3.geometry} material={materials.eagle_beak} />
    </group>
  )
}

useGLTF.preload('models/Eager Eagle/Eagle-transformed.glb')
